const ShowSectionName = Object.freeze({
    MSISDN: "MSISDN",
    ACCOUNT: "ACCOUNT",
    CAAP: "CAAP",
    FIX_PROCESS_CHANGED: "FIX_PROCESS_CHANGED",
    CART_WAS_CHANGED: "CART_WAS_CHANGED",
    INCOMPATIBLE_MARKET_MODAL: "INCOMPATIBLE_MARKET_MODAL",
    STAY_LOVE: "STAY_LOVE",
    CHECK_IS_CUSTOMER: "CHECK_IS_CUSTOMER",
    LEAD_FORM: "LEAD_FORM",
});
export default ShowSectionName;