import _ from "lodash";

const TransactionProcessType = {
    ACTIVATION: "ACTIVATION",
    MNP: "MNP",
    RETENTION: "RETENTION",
    MIGRATION_PRE_POST: "MIGRATION_PRE_POST",
    MNP_TWOSTEP: "MNP_TWOSTEP",
    MIGRATION_ZETAFON_POST: "MIGRATION_ZETAFON_POST",
    MIGRATION_NJU_POST_TO_POST: "MIGRATION_NJU_POST_TO_POST",
    MIGRATION_NJU_PRE_TO_POST: "MIGRATION_NJU_PRE_TO_POST",
    ASSIGNMENT: "ASSIGNMENT",
    ASSIGNMENT_DEATH: "ASSIGNMENT_DEATH",
    ASSIGNMENT_B2C_B2B: "ASSIGNMENT_B2C_B2B",
    ASSIGNMENT_B2C_JDG: "ASSIGNMENT_B2C_JDG",
    MNP_APPLICATION: "MNP_APPLICATION",
    MNP_APPLICATION_SECOND_STEP: "MNP_APPLICATION_SECOND_STEP",
    SALE_OF_GOODS: "SALE_OF_GOODS",
    INSTALMENT_SALES_OF_GOODS: "INSTALMENT_SALES_OF_GOODS",
    INSTALMENT_SALES_OF_GOODS_NC: "INSTALMENT_SALES_OF_GOODS_NC",
    isAssignment: process => _.includes(["ASSIGNMENT", "ASSIGNMENT_DEATH", "ASSIGNMENT_B2C_B2B", "ASSIGNMENT_B2C_JDG"], process),
    isMigration: process => _.includes(["MIGRATION_ZETAFON_POST", "MIGRATION_NJU_POST_TO_POST", "MIGRATION_NJU_PRE_TO_POST", "MNP", "MNP_TWOSTEP"], process),
    isTanto: process => _.includes(["INSTALMENT_SALES_OF_GOODS", "INSTALMENT_SALES_OF_GOODS_NC"], process),
};

export default TransactionProcessType;