const TvPackagesChoiceFilter = {
    TV_DEFAULT_CHOICE_PRODUCT: 'TV_DEFAULT_CHOICE_PRODUCT',
    TV_SECONDARY_CHOICE_PRODUCT: 'TV_SECONDARY_CHOICE_PRODUCT',
    TV_LOYALTY_DURATION_12: 'TV_LOYALTY_DURATION_12',
    TV_LOYALTY_DURATION_24: 'TV_LOYALTY_DURATION_24'
};

export default TvPackagesChoiceFilter;