export const GET_CUSTOMER_SERVICES_LIST = "fix/get/customerServices/List";
export const CUSTOMER_SERVICES_LIST_IS_LOADING = "fix/get/customerServices/List/loading";
export const CUSTOMER_SERVICES_LIST_IS_EMPTY = "fix/get/customerServices/List/empty";
export const MIGRATION_MODE = "MIGRATION_MODE";
export const FETCH_OFFERS = "FETCH_OFFERS";
export const FETCH_OFFERS_START = "FETCH_OFFERS_START";
export const CART_MOD_LOADING = "CART_MOD_LOADING";
export const MIGRATION_DATA_CLEAR = "MIGRATION_DATA_CLEAR";
export const FETCH_EXTRA_TV_CANALS = "FETCH_EXTRA_TV_CANALS";
export const SHOW_MODAL_ACTION = "SHOW_MODAL_ACTION";
export const CLOSE_TV_MODAL = "CLOSE_TV_MODAL";
export const FETCH_DOCUMENTS = "FETCH_DOCUMENTS";
export const UPDATE_DOCUMENTS = "UPDATE_DOCUMENTS";
export const UPDATE_FILTER_ID = "UPDATE_FILTER_ID";
export const UPDATE_PAGE_CONTEXT = "UPDATE_PAGE_CONTEXT";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const SHOW_KNA_MODAL_ACTION = "SHOW_KNA_MODAL_ACTION";
export const REGISTER_KNA_MODAL_ACTION = "REGISTER_KNA_MODAL_ACTION";
export const CLOSE_KNA_MODAL_ACTION = "CLOSE_KNA_MODAL_ACTION";
export const CHANGE_KNA_FORM_FIELD = "CHANGE_KNA_FORM_FIELD";
export const CHANGE_VOIP_FORM_FIELD = "CHANGE_VOIP_FORM_FIELD";
export const CLOSE_VOIP_MODAL_ACTION = "CLOSE_VOIP_MODAL_ACTION";
export const SELECT_VOIP_NUMBER = "SELECT_VOIP_NUMBER";
export const BEFORE_WWT = "BEFORE_WWT";
export const AFTER_WWT = "AFTER_WWT";
export const SAVE_SELECTED_OFFER_ID = "SAVE_SELECTED_OFFER_ID";
export const VOIP_STOP_LOADING_MODAL_ACTION = "VOIP_STOP_LOADING_MODAL_ACTION";
export const SHOW_PAYMENT_LINK_COMPONENT = "SHOW_PAYMENT_LINK_COMPONENT";
export const HIDE_PAYMENT_LINK_COMPONENT = "HIDE_PAYMENT_LINK_COMPONENT";
export const SAVE_WWT_ADDRESS = "SAVE_WWT_ADDRESS";
export const SELECT_LOYALTY = "SELECT_LOYALTY";
export const SHOW_CUSTOMER_SELECTED_MODAL_ACTION = "SHOW_CUSTOMER_SELECTED_MODAL_ACTION";
export const CLOSE_CUSTOMER_SELECTED_MODAL_ACTION = "CLOSE_CUSTOMER_SELECTED_MODAL_ACTION";
export const SERVICE_DETAILS_FETCHED = "SERVICE_DETAILS_FETCHED";
export const SERVICE_DETAILS_FETCHING = "SERVICE_DETAILS_FETCHING";
export const SHOW_CART_NOT_EMPTY_MODAL = "SHOW_CART_NOT_EMPTY_MODAL";
export const FETCH_OFFERS_STOP = "FETCH_OFFERS_STOP";
export const AFTER_SEARCH_CUSTOMER = "AFTER_SEARCH_CUSTOMER";
export const MIGRATION_VARIANTS_FETCHED = "MIGRATION_VARIANTS_FETCHED";
export const MIGRATION_VARIANTS_FETCHING = "MIGRATION_VARIANTS_FETCHING";
export const FORCE_AFTER_WWT = "FORCE_AFTER_WWT";

export const CLOSE_FORCE_SEARCH_MODAL_ACTION = "CLOSE_FORCE_SEARCH_MODAL_ACTION";
export const SHOW_FORCE_SEARCH_MODAL_ACTION = "SHOW_FORCE_SEARCH_MODAL_ACTION";

export const IS_LP = "IS_LP";
export const SAVE_BUNDLE_NOS = "SAVE_BUNDLE_NOS";

export const MOUNT_VOIP_MODAL_COMPONENT_ACTION = "MOUNT_VOIP_MODAL_COMPONENT_ACTION";


export const OPEN_ERROR_MODAL = "OPEN_ERROR_MODAL";
export const CLOSE_ERROR_MODAL = "CLOSE_ERROR_MODAL";

export const CART_SUMMARY_SEARCH_CUSTOMER_DONE = "CART_SUMMARY_SEARCH_CUSTOMER_DONE";
export const LP_SEARCH_CUSTOMER_DONE = "LP_SEARCH_CUSTOMER_DONE";

export const SHOW_SECONDARY_CHOICE_OFFER = "SHOW_SECONDARY_CHOICE_OFFER";
export const SHOW_BASE_OFFER = "SHOW_BASE_OFFER";

export const HIDE_WWT_COMPONENT = "HIDE_WWT_COMPONENT";
export const SHOW_WWT_COMPONENT = "SHOW_WWT_COMPONENT";

export const HIDE_WWT_MODAL = "HIDE_WWT_MODAL";
export const SHOW_WWT_MODAL = "SHOW_WWT_MODAL";
export const SET_REDIRECT_URL_AFTER_WWT = "SET_REDIRECT_URL_AFTER_WWT";


export const IS_DUPLICATE_ORDER = "IS_DUPLICATE_ORDER";
export const HAS_ACCESS_ROLE_TO_PROCESS_DUPLICATE_ORDER = "HAS_ACCESS_ROLE_TO_PROCESS_DUPLICATE_ORDER";
export const DUPLICATE_ORDER_FETCHING = "DUPLICATE_ORDER_FETCHING";
export const DUPLICATE_ORDER_RESET = "DUPLICATE_ORDER_RESET";
export const DUPLICATE_ORDER_FETCHED = "DUPLICATE_ORDER_FETCHED";
export const DUPLICATE_ORDER_IS_MODAL_OPENED = "DUPLICATE_ORDER_IS_MODAL_OPENED";
export const DUPLICATE_ORDER_DETAILS = "DUPLICATE_ORDER_DETAILS";
export const IS_MIGRATION = "IS_MIGRATION";

export const WWT_VALIDATION_MODAL = "WWT_VALIDATION_MODAL";
export const WWT_VALIDATION_MODAL_MESSAGE = "WWT_VALIDATION_MODAL_MESSAGE";

export const MARKET_SEGMENT = "MARKET_SEGMENT";
export const SET_HEADERS = "SET_HEADERS";

export const DESIGNATION_NUMBER = "DESIGNATION_NUMBER";
export const VOIP_SELECTION = "VOIP_SELECTION";
export const SHOW_VOIP_VARIANT_MODAL = "SHOW_VOIP_VARIANT_MODAL";
export const SHOW_VOIP_NUMBERS_MODAL = "SHOW_VOIP_NUMBERS_MODAL";
export const VOIP_VARIANT = "VOIP_VARIANT";
export const VOIP_NUMBER_SELECTED = "VOIP_NUMBER_SELECTED";
export const SAVE_VOIP_NUMBERS = "SAVE_VOIP_NUMBERS";
export const VOIP_NUMBERS_FETCHED = "VOIP_NUMBERS_FETCHED";
export const VOIP_NUMBERS_FETCHING = "VOIP_NUMBERS_FETCHING";

export const REDIRECT_TO_MIGRATIONS = "fix/redirectToMigrations";
export const MIGRATION_VARIANT_SELECTED = "fix/migrationVariant/selected";

export const PROMOTION_IS_AVAILABLE_START = "promotion/isAvailable/start";
export const PROMOTION_IS_AVAILABLE_LOADED = "promotion/isAvailable/";

export const SET_SALES_CHANNEL = "fix/salesChannel";