export const FETCH_SERVICES_TO_TRANSFER_START = "FETCH_SERVICES_TO_TRANSFER_START";
export const FETCH_SERVICES_TO_TRANSFER_END = "FETCH_SERVICES_TO_TRANSFER_END";
export const FETCH_SERVICES_TO_TRANSFER_ERROR = "FETCH_SERVICES_TO_TRANSFER_ERROR";
export const ACCOUNT_BALANCE_WITH_INSTALLMENT_PLAN = "ACCOUNT_BALANCE_WITH_INSTALLMENT_PLAN";

export const SELECT_PROCESS = "SELECT_PROCESS";
export const SELECT_SERVICE_TO_TRANSFER = "SELECT_SERVICE_TO_TRANSFER";
export const UNSELECT_SERVICE_TO_TRANSFER = "UNSELECT_SERVICE_TO_TRANSFER";

export const PACKAGE_DISCOUNT_CONFIRM_CHECKED = "PACKAGE_DISCOUNT_CONFIRM_CHECKED";
export const PACKAGE_DISCOUNT_CONFIRM_UNCHECKED = "PACKAGE_DISCOUNT_CONFIRM_UNCHECKED";

export const SELECTED_SERVICE_CHANGED = "SELECTED_SERVICE_CHANGED";