define(["exports"], function(E) {
    "use strict";
    Object.defineProperty(E, "__esModule", {
        value: !0
    }), E.SELECTED_SERVICE_CHANGED = E.PACKAGE_DISCOUNT_CONFIRM_UNCHECKED = E.PACKAGE_DISCOUNT_CONFIRM_CHECKED = E.UNSELECT_SERVICE_TO_TRANSFER = E.SELECT_SERVICE_TO_TRANSFER = E.SELECT_PROCESS = E.ACCOUNT_BALANCE_WITH_INSTALLMENT_PLAN = E.FETCH_SERVICES_TO_TRANSFER_ERROR = E.FETCH_SERVICES_TO_TRANSFER_END = E.FETCH_SERVICES_TO_TRANSFER_START = void 0;
    E.FETCH_SERVICES_TO_TRANSFER_START = "FETCH_SERVICES_TO_TRANSFER_START";
    E.FETCH_SERVICES_TO_TRANSFER_END = "FETCH_SERVICES_TO_TRANSFER_END";
    E.FETCH_SERVICES_TO_TRANSFER_ERROR = "FETCH_SERVICES_TO_TRANSFER_ERROR";
    E.ACCOUNT_BALANCE_WITH_INSTALLMENT_PLAN = "ACCOUNT_BALANCE_WITH_INSTALLMENT_PLAN";
    E.SELECT_PROCESS = "SELECT_PROCESS";
    E.SELECT_SERVICE_TO_TRANSFER = "SELECT_SERVICE_TO_TRANSFER";
    E.UNSELECT_SERVICE_TO_TRANSFER = "UNSELECT_SERVICE_TO_TRANSFER";
    E.PACKAGE_DISCOUNT_CONFIRM_CHECKED = "PACKAGE_DISCOUNT_CONFIRM_CHECKED";
    E.PACKAGE_DISCOUNT_CONFIRM_UNCHECKED = "PACKAGE_DISCOUNT_CONFIRM_UNCHECKED";
    E.SELECTED_SERVICE_CHANGED = "SELECTED_SERVICE_CHANGED"
});
//# sourceMappingURL=actionTypes.js.map